name: flutter_tdd_boilerplate
description: "Flutter TDD Boilerplate"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons:
  flutter_bloc:
  equatable:
  go_router:
  get_it:
  dartz:
  http:
  internet_connection_checker_plus:
  url_launcher:
  shared_preferences:
  fluttertoast:
  package_info_plus:
  device_info_plus:
  intl:
  shimmer:
  cached_network_image:
  connectivity_plus:
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^0.3.0
  mockito: ^5.4.4
  build_runner: ^2.4.11
  bloc_test: ^9.1.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/Roboto/Roboto-Black.ttf
          weight: 900
    - family: Inter
      fonts:
        - asset: assets/Inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/Inter/Inter-Black.ttf
          weight: 900